# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Running code
        run: |

          python Servidor.py


      - uses: stefanzweifel/git-auto-commit-action@v2
        with:
          commit_message: "Descargado archivos"
          branch: main
          # Optional glob pattern of files which should be added to the commit
          #file_pattern: /

          # Optional local file path to the repository
          repository: .

          # Optional commit user and author settings
          # commit_user_name: Actions Bot
          # commit_user_email: hectorflores329@gmail.com
          # commit_author: DataIntelligence BOT <hectorflores329@gmail.com>
          # push_options: '--force'
